# Generated by Django 5.2.3 on 2025-06-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedDocument',
            fields=[
                ('document_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('document_type', models.CharField(max_length=255)),
                ('document_date', models.DateField()),
                ('date_received', models.DateField()),
                ('received_by', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'completed_documents',
                'managed': False,
            },
        ),
    ]
