# Generated by Django 5.2.3 on 2025-06-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
    ]
