# Generated by Django 5.2.3 on 2025-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_forrepairproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondemnedProperty',
            fields=[
                ('property_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=255)),
                ('par_no', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('serial_no', models.CharField(max_length=255)),
                ('date_acquired', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_user', models.CharField(max_length=255)),
                ('estimated_life_use', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'condemned_properties',
                'managed': False,
            },
        ),
    ]
