# Generated by Django 5.2.3 on 2025-06-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
    ]
