# Generated by Django 5.2.3 on 2025-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('action_log', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
