# Generated by Django 5.2.3 on 2025-06-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': False},
        ),
    ]
