# Generated by Django 5.2.3 on 2025-06-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_logs',
        ),
    ]
