# Generated by Django 5.2.3 on 2025-06-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('access_level', models.CharField(max_length=255)),
            ],
        ),
    ]
